version: '3.2'

services:
  node:
    environment:
      - CI
      - DB_NAME=realworld_test
      - GITHUB_ACTIONS
      - GITHUB_HEAD_REF
      - GITHUB_REF
      - GITHUB_REPOSITORY
      - GITHUB_RUN_ID
      - GITHUB_SHA
      - GITHUB_WORKFLOW
      - NODE_ENV=test
      - PINO_LEVEL=silent
  postgres:
    volumes:
      - test_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=realworld_test

volumes:
  test_data:
