name: eslint

on: 
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
    eslint: 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: instal NVM
              run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
            - name: use Node.js 12.x
              env:
                NODE_VERSION: 14.17.0
              run: nvm install $NODE_VERSION
            - name: install dependencies
              run: npm install
            - name: lint with ESLint
              run: npm run lint