name: lint

jobs:
  eslint:
    runs-on: node:14.17.0-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Lint source code with ESLint
        run: npm run lint

  prettier:
    runs-on: node:14.17.0-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Lint source code with ESLint
        run: npm run check:format
